import { UserMockup } from '../models/user.model';

export const USERS_MOCKUP: UserMockup[] = [
  {
    id: '1',
    firstName: 'Kacper',
    lastName: 'Augustyn',
    email: 'Judasz@Barabasz',
    phoneNum: '123456',
    createdAt: new Date(),
    profilePicture: '../../../../../assets/images/profile-img.png',
    activationStatus: true,
  },
  {
    id: '2',
    firstName: 'Kacper',
    lastName: 'Augustyn',
    email: 'Judasz@Barabasz',
    phoneNum: '123456',
    createdAt: new Date(),
    profilePicture: '../../../../../assets/images/profile-img.png',
    activationStatus: true,
  },
  {
    id: '3',
    firstName: 'Kacper',
    lastName: 'Augustyn',
    email: 'Judasz@Barabasz',
    phoneNum: '123456',
    createdAt: new Date(),
    profilePicture: '../../../../../assets/images/profile-img.png',
    activationStatus: true,
  },
  {
    id: '4',
    firstName: 'Kacper',
    lastName: 'Augustyn',
    email: 'Judasz@Barabasz',
    phoneNum: '123456',
    createdAt: new Date(),
    profilePicture: '../../../../../assets/images/profile-img.png',
    activationStatus: true,
  },
  {
    id: '5',
    firstName: 'Kacper',
    lastName: 'Augustyn',
    email: 'Judasz@Barabasz',
    phoneNum: '123456',
    createdAt: new Date(),
    profilePicture: '../../../../../assets/images/profile-img.png',
    activationStatus: true,
  },
];
